### ISSUE TITLE
Bug: hash of CSS file does not change when referenced image changes

### ISSUE THREAD

**Issue by bannmann** [dernasherbrezon/fingerprint-maven-plugin#10]
Let's say your project consists of these files:

- `index.html` references `stylesheet.css`
- `stylesheet.css` references `background.png`
- `background.png`

Running the plugin once works as expected:

1. The image gets renamed according to its hash, and the reference to it in the CSS file is changed as well.
2. The CSS file gets renamed according to its hash, and the reference to it in the HTML file is changed as well.

Now you replace/edit the image file and run the plugin again:

1. The image gets renamed according to its _**new**_ hash, and the reference to it in the CSS file is also changed.
2. However, the CSS file is _**not**_ renamed compared to the previous situation!

It turns out that the plugin uses the hashes of the original source file's contents. But we did not change the _**source**_ CSS at all - it still references `background.png`!

The result is that in the HTML file, the reference to the CSS still has the same hash as before. Therefore, browsers will not reload the CSS, and will therefore not reload the image file!

This problem could be prevented if the plugin calculated the hashes of the _**modified**_ files, i.e. after it altered the contained references to other resources.

Workaround: do not use any image URLs in CSS. 😢

**Comment by dernasherbrezon** [comment]
Fixed in 3.9
